#!/bin/bash
#
export SCRIPT_URL="https://raw.githubusercontent.com/tic-tac-toe-io/wstty-agent/master/scripts/deployment/install-agent"
echo "for backward compatibility, the installation script in this repository is still kept..., but redirect to latest script in wstty-agent repository"
echo "running bash script from ${SCRIPT_URL} ..."
${BASH} -c "$(curl -sL ${SCRIPT_URL})"
